#!/usr/bin/env bash
# Scan installed agent skills on this machine and write an inventory markdown file.
# Does NOT install skills, does NOT invoke them, does NOT embed the list into the
# universal Agent OS kit (machine-local / project-local only).
#
# Usage:
#   bash scan-global-skills.sh [output-path]
# Default output: ./docs/agents/skill-inventory.local.md (cwd = repo root recommended)
#
# Env:
#   CLAUDE_SKILLS_DIRS — optional colon-separated extra roots to scan
set -euo pipefail
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:${PATH:-}"

OUT="${1:-./docs/agents/skill-inventory.local.md}"
mkdir -p "$(dirname "$OUT")"

# Portable roots (no hardcoded username beyond $HOME).
# Flat skill dirs: one folder per SKILL.md.
ROOTS=(
  "${HOME}/.claude/skills"
  "${HOME}/.agents/skills"
  "${HOME}/.agents/vendor/pstack/skills"
  "${HOME}/.codex/skills"
  "${HOME}/.cursor/skills"
  "${HOME}/.config/opencode/skills"
)
if [[ -n "${CLAUDE_SKILLS_ROOT:-}" && -d "${CLAUDE_SKILLS_ROOT}/skills" ]]; then
  ROOTS+=("${CLAUDE_SKILLS_ROOT}/skills")
fi
if [[ -n "${CLAUDE_SKILLS_DIRS:-}" ]]; then
  IFS=':' read -r -a _extra <<< "${CLAUDE_SKILLS_DIRS}"
  ROOTS+=("${_extra[@]}")
fi

# Plugin caches: SKILL.md is nested (hash / skills / name).
PLUGIN_ROOTS=(
  "${HOME}/.claude/plugins/cache"
  "${HOME}/.cursor/plugins/cache"
)

extract_field() {
  # $1=file $2=yaml key (name|description)
  local f="$1" key="$2"
  [[ -f "$f" ]] || return 0
  # frontmatter only (first --- block)
  awk '
    BEGIN { in_fm=0 }
    /^---[[:space:]]*$/ {
      if (in_fm==0) { in_fm=1; next }
      else { exit }
    }
    in_fm==1 {
      if ($0 ~ ("^" key ":[[:space:]]*")) {
        sub("^[^:]+:[[:space:]]*", "")
        print
        exit
      }
    }
  ' key="$key" "$f" 2>/dev/null || true
}

extract_github() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  # first github.com URL in skill doc
  grep -Eo 'https://github\.com/[[:alnum:]._-]+/[[:alnum:]._-]+' "$f" 2>/dev/null | head -1 || true
}

{
  echo "# Skill inventory (machine scan)"
  echo
  echo "_Generated by \`agent-os/scripts/scan-global-skills.sh\`. Local to this machine/repo."
  echo "This file **is the pointer**: any harness may \`Read\` a listed \`SKILL.md\`."
  echo "Not plan authority. Agents: **consider** rows that match the current phase; **decide** use or skip."
  echo "Do **not** invoke every skill every turn. Intensity caps (D0–D3 / I0–I4) still win._"
  echo "See \`agent-os/SKILL-ROOTS.md\` / \`references/skill-roots.md\` for what pointing can and cannot execute."
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo
  echo "## How any harness should use this"
  echo
  echo "1. User names the **project goal / sprint** (not a skill list)."
  echo "2. Agent reads \`DECISIONS.md\` + playbook + \`SKILL-ROOTS.md\` + this inventory."
  echo "3. Agent picks **0–3** skills, \`Read\`s that \`SKILL.md\` from the path below (do not wait for the host \`/skills\` menu)."
  echo "4. If a named runtime is missing, fallback via \`CAPABILITIES.md\` — do not block D0/I0."
  echo
  echo "## Scanned roots"
  echo
  for r in "${ROOTS[@]}" "${PLUGIN_ROOTS[@]}"; do
    if [[ -d "$r" ]]; then echo "- \`$r\`"; else echo "- \`$r\` _(missing)_"; fi
  done
  echo
  echo "## Installed skills"
  echo
  echo "| Name | Source dir | Description (short) | GitHub (if found) |"
  echo "|---|---|---|---|"

  seen=""
  for root in "${ROOTS[@]}"; do
    [[ -d "$root" ]] || continue
    # one level of skill folders
    for dir in "$root"/*; do
      [[ -d "$dir" ]] || continue
      base="$(basename "$dir")"
      # skip hidden
      [[ "$base" == .* ]] && continue
      skill_md=""
      if [[ -f "$dir/SKILL.md" ]]; then skill_md="$dir/SKILL.md"
      elif [[ -f "$dir/skill.md" ]]; then skill_md="$dir/skill.md"
      fi
      name="$base"
      desc=""
      gh=""
      if [[ -n "$skill_md" ]]; then
        n="$(extract_field "$skill_md" name)"
        [[ -n "$n" ]] && name="$n"
        desc="$(extract_field "$skill_md" description)"
        # trim long descriptions
        if [[ ${#desc} -gt 120 ]]; then desc="${desc:0:117}..."; fi
        # flatten newlines/pipes
        desc="$(printf '%s' "$desc" | tr '\n|' '  ')"
        gh="$(extract_github "$skill_md")"
      fi
      key="${name}|${root}"
      case "$seen" in
        *"|$key|"*) continue ;;
      esac
      seen="${seen}|$key|"
      rel="${dir/#$HOME/~}"
      echo "| \`${name}\` | \`${rel}\` | ${desc:-_(no description)_} | ${gh:-—} |"
    done
  done

  emit_skill_row() {
    local skill_md="$1"
    local dir name desc gh rel n
    dir="$(dirname "$skill_md")"
    name="$(basename "$dir")"
    desc=""
    gh=""
    n="$(extract_field "$skill_md" name)"
    [[ -n "$n" ]] && name="$n"
    desc="$(extract_field "$skill_md" description)"
    if [[ ${#desc} -gt 120 ]]; then desc="${desc:0:117}..."; fi
    desc="$(printf '%s' "$desc" | tr '\n|' '  ')"
    gh="$(extract_github "$skill_md")"
    rel="${dir/#$HOME/~}"
    key="${name}|${dir}"
    case "$seen" in
      *"|$key|"*) return 0 ;;
    esac
    seen="${seen}|$key|"
    echo "| \`${name}\` | \`${rel}\` | ${desc:-_(no description)_} | ${gh:-—} |"
  }

  for proot in "${PLUGIN_ROOTS[@]}"; do
    [[ -d "$proot" ]] || continue
    # Nested plugin skills (pstack, Matt, ponytail, …)
    while IFS= read -r skill_md; do
      [[ -n "$skill_md" ]] || continue
      emit_skill_row "$skill_md"
    done < <(find "$proot" -name SKILL.md -print 2>/dev/null | head -n 800 || true)
  done

  echo
  echo "## Phase hint map (universal defaults — project overlay may narrow)"
  echo
  echo "| Phase | Prefer considering | Usually skip |"
  echo "|---|---|---|"
  echo "| Orient | graft / graphify / find-skills | design-taste packs, pptx/resume |"
  echo "| Decide | wayfinder, grilling, llm-council (D3 only), office-hours | ship/land-and-deploy |"
  echo "| Build | ponytail, implement/tdd, careful | multi review stack |"
  echo "| Prove | qa, webapp-testing, browse, benchmark | resume-writing, imagegen |"
  echo "| Harden | critic **or** multi-lens-review **or** review (pick one) | stacked review theater |"
  echo "| Write-up | humanizer, doc-coauthoring, document-* | gstack full team |"
  echo
  echo "## Regenerating"
  echo
  echo '```bash'
  echo "bash \"\${AGENT_OS_HOME:-\$HOME/.claude/skills/agent-os}/scripts/scan-global-skills.sh\" docs/agents/skill-inventory.local.md"
  echo '```'
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^|' "$OUT" | head -1) table lines incl. header)"
